name: SpoutKeyCommands
main: com.yurijware.bukkit.SpoutKeyCommands.SpoutKeyCommands
version: 2.0
database: true
authors: [Yurij]
depends: [Spout]
softdepend: [PermissionsEx,Permissions]

description: >
            Allows players to set commands to keys
            
permissions:
  SpoutKeyCommands.*:
    description: Allows you to use all commands and functionality
    default: op
    children:
      SpoutKeyCommands.use: true
      SpoutKeyCommands.setglobal: true
      SpoutKeyCommands.check-other: true
      SpoutKeyCommands.admin: true
      
  SpoutKeyCommands.use:
    description: Allows you to use commands
      
  SpoutKeyCommands.set-global:
    description: Allows you to set global commands
    
  SpoutKeyCommands.check-other:
    description: Allows you to check others commands
    
  SpoutKeyCommands.admin:
    description: Allows you change admin config
    
commands:
  SpoutKeyCommands:
    aliases: [skc]
    description: Warps you to another world
    usage: |
           /<command> set <command> - Set personal key
           /<command> gset <command> - Set global key
           /<command> unset - Unset personal key
           /<command> gunset - Unset global key
           /<command> check global|personal [player] - Check wich keys are set
           /<command> config - Check availible configurations
           /<command> clear - Clear all personal keys
           /<command> gclear - Clear all global keys
           