name: SpoutKeyCommands
main: com.yurijware.bukkit.SpoutKeyCommands.SpoutKeyCommands
version: 1.2
authors: [Yurij]
softdepend: [Spout,PermissionsEx,Permissions]

description: >
            Allows players to set commands to keys
            
permissions:
  SpoutKeyCommands.user:
    description: Allows you to use normal user commands and functionality
    default: true
    children:
      SpoutKeyCommands.set.personal: true
      SpoutKeyCommands.use.personal: true
      SpoutKeyCommands.use.global: true
      SpoutKeyCommands.check.self: true
      
  SpoutKeyCommands.*:
    description: Allows you to use all commands and functionality
    default: op
    children:
      SpoutKeyCommands.set.*: true
      SpoutKeyCommands.use.*: true
      SpoutKeyCommands.check.*: true
      SpoutKeyCommands.reload: true
      
  SpoutKeyCommands.use.*:
    description: Allows you to use both personal and global commands
    children:
      SpoutKeyCommands.use.personal: true
      SpoutKeyCommands.use.global: true
      
  SpoutKeyCommands.use.personal:
    description: Allows you to use personal commands
    default: true
    
  SpoutKeyCommands.use.global:
    description: Allows you to use global commands
    default: true
    
  SpoutKeyCommands.set.*:
    description: Allows you to set both personal and global commands
    children:
      SpoutKeyCommands.set.personal: true
      SpoutKeyCommands.set.global: true
      
  SpoutKeyCommands.set.personal:
    description: Allows you to set personal commands
    default: true
    
  SpoutKeyCommands.set.global:
    description: Allows you to set global commands
    
  SpoutKeyCommands.check.*:
    description: Allows you to check both own and others commands
    children:
      SpoutKeyCommands.check.self: true
      SpoutKeyCommands.check.other: true
      
  SpoutKeyCommands.check.self:
    description: Allows you to check your own commands
    default: true
    
  SpoutKeyCommands.check.other:
    description: Allows you to check others commands
    
  SpoutKeyCommands.reload:
    description: Allows you to save and load database config
    
commands:
  SpoutKeyCommands:
    aliases: [skc]
    description: Warps you to another world
    usage: |
           /<command> set <command> - Set personal command
           /<command> gset <command> - Set global command
           /<command> unset - Unset personal command
           /<command> gunset - Unset global command
           /<command> check [player] - Check wich commands are set
           /<command> clear - Clears all personal commands
           /<command> gclear - Clears all global commands
           /<command> save - Saves the commands to the database
           /<command> load - Loads the commands from the database
           